export interface AlertData {
  id: number;
  status: 'critical' | 'warning';
  issue: string;
  activity: string;
  eventId: string;
  region: string;
  site: string;
  rig: string;
  camera: string;
  dateTime: string;
  zoneType?: string;
  location?: string;
}

export const alertData: AlertData[] = [
  {
    id: 1,
    status: 'critical',
    issue: 'Human Detected',
    activity: 'Active',
    eventId: 'EVT-9082',
    region: 'West',
    site: 'Midland Site',
    rig: 'Rig 145',
    camera: 'Cam 04 - Pipe Deck',
    dateTime: '10/24/2025 12:45 PM',
    zoneType: 'Red Zone',
    location: 'Drill floor 9'
  },
  {
    id: 2,
    status: 'warning',
    issue: 'Human detected',
    activity: 'Recent',
    eventId: 'EVT-9081',
    region: 'West',
    site: 'Midland Site',
    rig: 'Rig 145',
    camera: 'Camera 04',
    dateTime: '10/24/2025 12:40 PM',
    zoneType: 'Yellow Zone',
    location: 'Drill floor 9'
  },
  {
    id: 3,
    status: 'warning',
    issue: 'Human detected',
    activity: 'Recent',
    eventId: 'EVT-9078',
    region: 'West',
    site: 'Midland Site',
    rig: 'Rig 145',
    camera: 'Cam 04 - Pipe Deck',
    dateTime: '10/24/2025 11:15 AM',
    zoneType: 'Yellow Zone',
    location: 'Drill floor 9'
  },
  {
    id: 4,
    status: 'warning',
    issue: 'Human detected',
    activity: 'Recent',
    eventId: 'EVT-9075',
    region: 'West',
    site: 'Midland Site',
    rig: 'Rig 145',
    camera: 'Camera 04',
    dateTime: '10/24/2025 09:30 AM',
    zoneType: 'Yellow Zone',
    location: 'Drill floor 9'
  },
  {
    id: 5,
    status: 'warning',
    issue: 'Human detected',
    activity: 'Recent',
    eventId: 'EVT-9060',
    region: 'West',
    site: 'Midland Site',
    rig: 'Rig 145',
    camera: 'Cam 04 - Pipe Deck',
    dateTime: '10/23/2025 03:22 PM',
    zoneType: 'Yellow Zone',
    location: 'Drill floor 9'
  },
  {
    id: 6,
    status: 'warning',
    issue: 'Equipment detected – Yellow Zone',
    activity: 'Recent',
    eventId: 'EVT-9059',
    region: 'West',
    site: 'Midland Site',
    rig: 'Rig 145',
    camera: 'Cam 02 - Pipe Deck',
    dateTime: '10/23/2025 02:55 PM',
    zoneType: 'Yellow Zone',
    location: 'Pipe deck'
  },
  {
    id: 7,
    status: 'warning',
    issue: 'Human detected',
    activity: 'Recent',
    eventId: 'EVT-9058',
    region: 'West',
    site: 'Midland Site',
    rig: 'Rig 145',
    camera: 'Cam 03 - Mud Pumps',
    dateTime: '10/23/2025 02:18 PM',
    zoneType: 'Yellow Zone',
    location: 'Mud pump bay'
  },
  {
    id: 8,
    status: 'warning',
    issue: 'Vehicle detected – Yellow Zone',
    activity: 'Recent',
    eventId: 'EVT-9057',
    region: 'West',
    site: 'Midland Site',
    rig: 'Rig 146',
    camera: 'Cam 01 - Drill Floor',
    dateTime: '10/23/2025 01:46 PM',
    zoneType: 'Yellow Zone',
    location: 'Entry lane'
  },
  {
    id: 9,
    status: 'warning',
    issue: 'Human detected',
    activity: 'Recent',
    eventId: 'EVT-9056',
    region: 'East',
    site: 'Site 1',
    rig: 'Rig 145',
    camera: 'Cam 04 - Pipe Deck',
    dateTime: '10/23/2025 01:10 PM',
    zoneType: 'Yellow Zone',
    location: 'Pipe deck'
  },
  {
    id: 10,
    status: 'warning',
    issue: 'Human detected',
    activity: 'Recent',
    eventId: 'EVT-9055',
    region: 'East',
    site: 'Site 2',
    rig: 'Rig 146',
    camera: 'Cam 02 - Pipe Deck',
    dateTime: '10/23/2025 12:48 PM',
    zoneType: 'Yellow Zone',
    location: 'Catwalk'
  },
  {
    id: 11,
    status: 'warning',
    issue: 'Equipment detected – Yellow Zone',
    activity: 'Recent',
    eventId: 'EVT-9054',
    region: 'East',
    site: 'Site 3',
    rig: 'Rig 147',
    camera: 'Cam 01 - Drill Floor',
    dateTime: '10/23/2025 12:05 PM',
    zoneType: 'Yellow Zone',
    location: 'Tool staging area'
  },
  {
    id: 12,
    status: 'warning',
    issue: 'Vehicle detected – Yellow Zone',
    activity: 'Recent',
    eventId: 'EVT-9053',
    region: 'East',
    site: 'Site 4',
    rig: 'Rig 148',
    camera: 'Cam 03 - Mud Pumps',
    dateTime: '10/23/2025 11:44 AM',
    zoneType: 'Yellow Zone',
    location: 'Service road'
  },
  {
    id: 13,
    status: 'warning',
    issue: 'Human detected',
    activity: 'Recent',
    eventId: 'EVT-9052',
    region: 'West',
    site: 'Site 5',
    rig: 'Rig 151',
    camera: 'Cam 04 - Pipe Deck',
    dateTime: '10/23/2025 11:12 AM',
    zoneType: 'Yellow Zone',
    location: 'Pipe deck'
  },
  {
    id: 14,
    status: 'warning',
    issue: 'Equipment detected – Yellow Zone',
    activity: 'Recent',
    eventId: 'EVT-9051',
    region: 'West',
    site: 'Site 6',
    rig: 'Rig 153',
    camera: 'Cam 02 - Pipe Deck',
    dateTime: '10/23/2025 10:41 AM',
    zoneType: 'Yellow Zone',
    location: 'BOP access'
  },
  {
    id: 15,
    status: 'warning',
    issue: 'Human detected',
    activity: 'Recent',
    eventId: 'EVT-9050',
    region: 'West',
    site: 'Site 7',
    rig: 'Rig 154',
    camera: 'Cam 01 - Drill Floor',
    dateTime: '10/23/2025 10:14 AM',
    zoneType: 'Yellow Zone',
    location: 'Drill floor'
  },
  {
    id: 16,
    status: 'warning',
    issue: 'Vehicle detected – Yellow Zone',
    activity: 'Recent',
    eventId: 'EVT-9049',
    region: 'West',
    site: 'Site 8',
    rig: 'Rig 155',
    camera: 'Cam 03 - Mud Pumps',
    dateTime: '10/23/2025 09:52 AM',
    zoneType: 'Yellow Zone',
    location: 'Laydown yard'
  },
  {
    id: 17,
    status: 'warning',
    issue: 'Human detected',
    activity: 'Recent',
    eventId: 'EVT-9048',
    region: 'North',
    site: 'Site 9',
    rig: 'Rig 156',
    camera: 'Cam 04 - Pipe Deck',
    dateTime: '10/23/2025 09:24 AM',
    zoneType: 'Yellow Zone',
    location: 'Pipe deck'
  },
  {
    id: 18,
    status: 'warning',
    issue: 'Equipment detected – Yellow Zone',
    activity: 'Recent',
    eventId: 'EVT-9047',
    region: 'North',
    site: 'Site 10',
    rig: 'Rig 157',
    camera: 'Cam 02 - Pipe Deck',
    dateTime: '10/23/2025 08:56 AM',
    zoneType: 'Yellow Zone',
    location: 'Top drive zone'
  },
  {
    id: 19,
    status: 'warning',
    issue: 'Human detected',
    activity: 'Recent',
    eventId: 'EVT-9046',
    region: 'North',
    site: 'Site 10',
    rig: 'Rig 158',
    camera: 'Cam 01 - Drill Floor',
    dateTime: '10/23/2025 08:23 AM',
    zoneType: 'Yellow Zone',
    location: 'Drill floor'
  },
  {
    id: 20,
    status: 'warning',
    issue: 'Vehicle detected – Yellow Zone',
    activity: 'Recent',
    eventId: 'EVT-9045',
    region: 'North',
    site: 'Site 11',
    rig: 'Rig 159',
    camera: 'Cam 03 - Mud Pumps',
    dateTime: '10/23/2025 07:58 AM',
    zoneType: 'Yellow Zone',
    location: 'Parking bay'
  },
  {
    id: 21,
    status: 'warning',
    issue: 'Human detected',
    activity: 'Recent',
    eventId: 'EVT-9044',
    region: 'North',
    site: 'Site 12',
    rig: 'Rig 160',
    camera: 'Cam 04 - Pipe Deck',
    dateTime: '10/23/2025 07:31 AM',
    zoneType: 'Yellow Zone',
    location: 'Pipe handling area'
  },
  {
    id: 22,
    status: 'warning',
    issue: 'Equipment detected – Yellow Zone',
    activity: 'Recent',
    eventId: 'EVT-9043',
    region: 'South',
    site: 'Site 13',
    rig: 'Rig 161',
    camera: 'Cam 02 - Pipe Deck',
    dateTime: '10/23/2025 07:06 AM',
    zoneType: 'Yellow Zone',
    location: 'BOP deck'
  },
  {
    id: 23,
    status: 'warning',
    issue: 'Human detected',
    activity: 'Recent',
    eventId: 'EVT-9042',
    region: 'South',
    site: 'Site 14',
    rig: 'Rig 162',
    camera: 'Cam 01 - Drill Floor',
    dateTime: '10/23/2025 06:42 AM',
    zoneType: 'Yellow Zone',
    location: 'Drill floor'
  },
  {
    id: 24,
    status: 'warning',
    issue: 'Vehicle detected – Yellow Zone',
    activity: 'Recent',
    eventId: 'EVT-9041',
    region: 'South',
    site: 'Site 15',
    rig: 'Rig 163',
    camera: 'Cam 03 - Mud Pumps',
    dateTime: '10/23/2025 06:18 AM',
    zoneType: 'Yellow Zone',
    location: 'Loading point'
  },
  {
    id: 25,
    status: 'warning',
    issue: 'Human detected',
    activity: 'Recent',
    eventId: 'EVT-9040',
    region: 'South',
    site: 'Site 16',
    rig: 'Rig 165',
    camera: 'Cam 04 - Pipe Deck',
    dateTime: '10/23/2025 05:55 AM',
    zoneType: 'Yellow Zone',
    location: 'Pipe rack'
  },
];
